language: php

php:
  - 5.2
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test2;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test2;' -U postgres; fi"
  - cp ./vendors/Travis/database.php ./app/Config/database.php
  - chmod -R 777 ./app/tmp
  - sudo node ./vendors/Travis/socket.js &

script:
  - ./lib/Cake/Console/cake testsuite core AllTests --stderr

notifications:
  email: false

branches:
  only:
    - 2.0-travis
